### ISSUE TITLE
Make analysis of CML min-max data possible

### ISSUE THREAD

**Issue by cchwala** [pycomlink/pycomlink#21]
Since in many countries only min-max data of CML networks is available for analysis (typically via the "performance reports" of the network management system), `pycomlink` should also handle these kind of data.

Necessary steps:

- [x] Read/write cmlh5 with min-max data with the default columns `tx_min`, `tx_max`, `rx_min` and `rx_max`. This must be done without breaking read/write of instantaneous data, which by default only has a `tx` and `rx` column. (solved in #23)
- [x] Add processing functions for min-max data (solved in #37)
- [x] Add example data and example notebook (solved in #45)
